server:
  port: 10086
logging:
  config: classpath:log4j2.xml
spring:
  datasource:
    url: jdbc:postgresql://10.3.200.10:5432/zhoujiadu?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: zjd
    password: zjd
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update